INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (1, 'STEM Scholarship', 1322, 123);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (2, 'Women in Technology Scholarship', 8680, 111);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (3, 'Arts Scholarship', 9307, 82);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (4, 'Women in Technology Scholarship', 3026, 129);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (5, 'Financial Aid Scholarship', 8024, 156);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (6, 'Financial Aid Scholarship', 2674, 125);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (7, 'Science Scholarship', 4908, 150);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (8, 'STEM Scholarship', 2101, 187);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (9, 'Research Grant', 9710, 167);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (10, 'STEM Scholarship', 4824, 158);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (11, 'Music Scholarship', 5887, 199);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (12, 'Financial Aid Scholarship', 1753, 78);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (13, 'STEM Scholarship', 9544, 107);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (14, 'Community Service Scholarship', 1064, 148);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (15, 'International Student Scholarship', 7305, 35);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (16, 'Minority Scholarship', 4995, 165);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (17, 'Healthcare Scholarship', 2853, 147);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (18, 'Excellence Scholarship', 5867, 185);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (19, 'Excellence Scholarship', 7179, 84);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (20, 'Diversity Scholarship', 5609, 127);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (21, 'Research Grant', 2585, 177);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (22, 'Arts Scholarship', 6769, 21);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (23, 'Minority Scholarship', 1052, 178);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (24, 'Academic Achievement Scholarship', 6110, 104);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (25, 'Music Scholarship', 2350, 123);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (26, 'STEM Scholarship', 8607, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (27, 'Innovation Scholarship', 9758, 96);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (28, 'Minority Scholarship', 7753, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (29, 'Academic Achievement Scholarship', 9561, 130);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (30, 'Healthcare Scholarship', 3539, 57);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (31, 'Financial Aid Scholarship', 7078, 126);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (32, 'Music Scholarship', 9143, 133);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (33, 'Creative Writing Scholarship', 8660, 161);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (34, 'Music Scholarship', 9121, 69);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (35, 'Healthcare Scholarship', 6853, 102);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (36, 'Excellence Scholarship', 6543, 119);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (37, 'Athletic Scholarship', 9167, 127);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (38, 'Women in Technology Scholarship', 4166, 143);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (39, 'Merit Scholarship', 1707, 41);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (40, 'International Student Scholarship', 3050, 97);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (41, 'STEM Scholarship', 5175, 86);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (42, 'Sports Scholarship', 5472, 194);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (43, 'Minority Scholarship', 8713, 80);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (44, 'Innovation Scholarship', 3674, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (45, 'Innovation Scholarship', 4113, 161);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (46, 'Healthcare Scholarship', 6968, 57);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (47, 'Healthcare Scholarship', 2595, 43);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (48, 'Creative Writing Scholarship', 7259, 168);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (49, 'Academic Achievement Scholarship', 6786, 55);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (50, 'Minority Scholarship', 3986, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (51, 'Minority Scholarship', 8619, 78);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (52, 'Creative Writing Scholarship', 4245, 186);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (53, 'Sports Scholarship', 4421, 168);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (54, 'Financial Aid Scholarship', 4315, 171);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (55, 'Excellence Scholarship', 3134, 64);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (56, 'Academic Achievement Scholarship', 2047, 200);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (57, 'Athletic Scholarship', 7871, 187);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (58, 'Leadership Scholarship', 6391, 125);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (59, 'Leadership Scholarship', 8818, 147);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (60, 'Creative Writing Scholarship', 2142, 111);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (61, 'Women in Technology Scholarship', 8256, 192);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (62, 'Community Service Scholarship', 7771, 181);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (63, 'Community Service Scholarship', 2709, 180);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (64, 'Healthcare Scholarship', 8042, 69);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (65, 'Arts Scholarship', 2950, 133);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (66, 'International Student Scholarship', 9622, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (67, 'Merit Scholarship', 5246, 139);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (68, 'Merit Scholarship', 6694, 194);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (69, 'Diversity Scholarship', 7733, 107);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (70, 'Community Service Scholarship', 4151, 23);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (71, 'Leadership Scholarship', 1421, 138);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (72, 'Athletic Scholarship', 2352, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (73, 'Innovation Scholarship', 5423, 70);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (74, 'Financial Aid Scholarship', 6280, 46);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (75, 'Diversity Scholarship', 2441, 60);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (76, 'Creative Writing Scholarship', 6920, 93);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (77, 'Sports Scholarship', 2277, 76);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (78, 'Diversity Scholarship', 3421, 88);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (79, 'Music Scholarship', 5063, 122);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (80, 'Sports Scholarship', 3519, 170);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (81, 'Music Scholarship', 9166, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (82, 'Athletic Scholarship', 7247, 198);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (83, 'Innovation Scholarship', 8410, 54);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (84, 'Financial Aid Scholarship', 5084, 168);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (85, 'Innovation Scholarship', 9003, 162);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (86, 'Merit Scholarship', 3343, 127);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (87, 'Excellence Scholarship', 7428, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (88, 'Music Scholarship', 5634, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (89, 'Healthcare Scholarship', 7642, 164);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (90, 'International Student Scholarship', 2280, 197);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (91, 'STEM Scholarship', 6566, 180);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (92, 'Community Service Scholarship', 8898, 106);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (93, 'Arts Scholarship', 2885, 66);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (94, 'Innovation Scholarship', 6135, 65);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (95, 'Athletic Scholarship', 1997, 29);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (96, 'Merit Scholarship', 2111, 109);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (97, 'International Student Scholarship', 6818, 173);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (98, 'Science Scholarship', 5279, 158);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (99, 'Women in Technology Scholarship', 5990, 112);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (100, 'Women in Technology Scholarship', 2916, 152);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (101, 'Merit Scholarship', 2820, 57);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (102, 'Community Service Scholarship', 2665, 135);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (103, 'Minority Scholarship', 6729, 159);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (104, 'Community Service Scholarship', 9936, 136);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (105, 'Academic Achievement Scholarship', 4554, 171);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (106, 'Innovation Scholarship', 5272, 91);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (107, 'Community Service Scholarship', 7923, 180);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (108, 'International Student Scholarship', 9145, 116);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (109, 'Minority Scholarship', 3035, 190);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (110, 'Research Grant', 4378, 103);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (111, 'Science Scholarship', 1449, 187);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (112, 'Leadership Scholarship', 8253, 102);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (113, 'Leadership Scholarship', 2570, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (114, 'Sports Scholarship', 8971, 170);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (115, 'Excellence Scholarship', 7014, 82);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (116, 'STEM Scholarship', 2443, 88);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (117, 'STEM Scholarship', 7367, 58);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (118, 'Athletic Scholarship', 5480, 38);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (119, 'Arts Scholarship', 9750, 121);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (120, 'Excellence Scholarship', 1933, 78);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (121, 'Music Scholarship', 5608, 108);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (122, 'Women in Technology Scholarship', 3765, 52);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (123, 'International Student Scholarship', 3372, 142);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (124, 'Music Scholarship', 7990, 186);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (125, 'International Student Scholarship', 7849, 81);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (126, 'Women in Technology Scholarship', 7925, 101);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (127, 'Healthcare Scholarship', 1713, 197);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (128, 'Athletic Scholarship', 5452, 83);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (129, 'Research Grant', 9094, 45);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (130, 'Excellence Scholarship', 9784, 137);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (131, 'Excellence Scholarship', 7953, 82);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (132, 'Creative Writing Scholarship', 4089, 119);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (133, 'Merit Scholarship', 6903, 146);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (134, 'International Student Scholarship', 7299, 195);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (135, 'Minority Scholarship', 7042, 124);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (136, 'Excellence Scholarship', 2958, 118);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (137, 'Athletic Scholarship', 5562, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (138, 'Healthcare Scholarship', 3117, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (139, 'Music Scholarship', 7684, 40);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (140, 'Arts Scholarship', 9185, 35);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (141, 'Diversity Scholarship', 4536, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (142, 'Research Grant', 6855, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (143, 'Leadership Scholarship', 7907, 34);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (144, 'Research Grant', 2890, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (145, 'Leadership Scholarship', 5412, 188);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (146, 'STEM Scholarship', 1737, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (147, 'Healthcare Scholarship', 2643, 189);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (148, 'Financial Aid Scholarship', 9754, 51);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (149, 'Excellence Scholarship', 7674, 53);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (150, 'Excellence Scholarship', 3004, 159);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (151, 'International Student Scholarship', 9848, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (152, 'Healthcare Scholarship', 6961, 199);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (153, 'STEM Scholarship', 2276, 176);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (154, 'Financial Aid Scholarship', 1115, 31);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (155, 'Music Scholarship', 8376, 148);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (156, 'Research Grant', 5924, 75);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (157, 'Excellence Scholarship', 5902, 189);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (158, 'Minority Scholarship', 7304, 135);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (159, 'Science Scholarship', 9857, 95);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (160, 'Leadership Scholarship', 4688, 190);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (161, 'Academic Achievement Scholarship', 2655, 134);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (162, 'International Student Scholarship', 2677, 83);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (163, 'Excellence Scholarship', 4717, 175);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (164, 'Leadership Scholarship', 7156, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (165, 'Science Scholarship', 5406, 81);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (166, 'Healthcare Scholarship', 4303, 27);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (167, 'Innovation Scholarship', 6726, 111);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (168, 'Academic Achievement Scholarship', 3977, 157);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (169, 'STEM Scholarship', 5977, 157);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (170, 'Women in Technology Scholarship', 1366, 115);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (171, 'Creative Writing Scholarship', 5306, 54);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (172, 'Sports Scholarship', 3998, 189);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (173, 'Innovation Scholarship', 2973, 185);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (174, 'Leadership Scholarship', 2050, 113);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (175, 'Athletic Scholarship', 6511, 25);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (176, 'Merit Scholarship', 6350, 64);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (177, 'Community Service Scholarship', 3744, 131);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (178, 'Merit Scholarship', 7926, 118);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (179, 'Healthcare Scholarship', 8286, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (180, 'Science Scholarship', 3243, 184);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (181, 'Athletic Scholarship', 6066, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (182, 'Music Scholarship', 8843, 85);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (183, 'STEM Scholarship', 2367, 24);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (184, 'Arts Scholarship', 3058, 171);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (185, 'Arts Scholarship', 8562, 92);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (186, 'Sports Scholarship', 9339, 120);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (187, 'Sports Scholarship', 2155, 29);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (188, 'Creative Writing Scholarship', 5082, 137);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (189, 'Research Grant', 8527, 138);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (190, 'Creative Writing Scholarship', 4800, 113);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (191, 'Athletic Scholarship', 3503, 40);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (192, 'STEM Scholarship', 9132, 146);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (193, 'Healthcare Scholarship', 3486, 193);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (194, 'Music Scholarship', 1353, 192);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (195, 'International Student Scholarship', 1141, 93);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (196, 'STEM Scholarship', 3994, 171);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (197, 'Research Grant', 5971, 152);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (198, 'Leadership Scholarship', 9179, 161);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (199, 'Financial Aid Scholarship', 1518, 174);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (200, 'Creative Writing Scholarship', 9675, 130);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (201, 'Healthcare Scholarship', 7194, 61);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (202, 'Research Grant', 6704, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (203, 'Women in Technology Scholarship', 4267, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (204, 'Women in Technology Scholarship', 8970, 101);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (205, 'Women in Technology Scholarship', 3123, 68);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (206, 'Innovation Scholarship', 9285, 113);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (207, 'Leadership Scholarship', 6212, 50);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (208, 'Women in Technology Scholarship', 6530, 188);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (209, 'Sports Scholarship', 8133, 79);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (210, 'Excellence Scholarship', 8185, 35);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (211, 'Healthcare Scholarship', 1538, 48);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (212, 'Leadership Scholarship', 6490, 136);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (213, 'Sports Scholarship', 1967, 113);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (214, 'Women in Technology Scholarship', 8864, 122);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (215, 'Science Scholarship', 5272, 193);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (216, 'Creative Writing Scholarship', 5320, 144);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (217, 'Healthcare Scholarship', 3762, 80);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (218, 'Leadership Scholarship', 3717, 169);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (219, 'Science Scholarship', 8598, 29);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (220, 'Research Grant', 8648, 152);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (221, 'Creative Writing Scholarship', 6775, 73);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (222, 'Merit Scholarship', 7168, 141);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (223, 'Sports Scholarship', 4173, 185);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (224, 'Research Grant', 1507, 58);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (225, 'Financial Aid Scholarship', 6479, 87);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (226, 'Academic Achievement Scholarship', 8783, 82);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (227, 'Financial Aid Scholarship', 8661, 146);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (228, 'Healthcare Scholarship', 7300, 65);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (229, 'Community Service Scholarship', 5763, 84);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (230, 'Minority Scholarship', 6678, 92);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (231, 'Merit Scholarship', 4016, 87);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (232, 'Financial Aid Scholarship', 9436, 152);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (233, 'Healthcare Scholarship', 3824, 119);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (234, 'Research Grant', 5831, 53);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (235, 'Athletic Scholarship', 4261, 63);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (236, 'Minority Scholarship', 7235, 83);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (237, 'Merit Scholarship', 9164, 57);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (238, 'Community Service Scholarship', 4684, 164);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (239, 'Diversity Scholarship', 6559, 43);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (240, 'Science Scholarship', 4948, 72);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (241, 'Leadership Scholarship', 4015, 92);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (242, 'Community Service Scholarship', 2524, 162);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (243, 'Academic Achievement Scholarship', 2602, 64);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (244, 'Merit Scholarship', 4255, 109);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (245, 'Community Service Scholarship', 3096, 113);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (246, 'Leadership Scholarship', 3458, 79);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (247, 'Merit Scholarship', 8426, 129);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (248, 'Diversity Scholarship', 8714, 110);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (249, 'STEM Scholarship', 9253, 148);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (250, 'Music Scholarship', 9135, 133);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (251, 'Arts Scholarship', 5944, 95);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (252, 'STEM Scholarship', 5769, 20);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (253, 'Arts Scholarship', 7317, 154);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (254, 'Community Service Scholarship', 8558, 171);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (255, 'International Student Scholarship', 3465, 188);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (256, 'Diversity Scholarship', 3000, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (257, 'Community Service Scholarship', 2192, 128);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (258, 'STEM Scholarship', 6742, 128);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (259, 'Arts Scholarship', 7936, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (260, 'International Student Scholarship', 5969, 104);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (261, 'Athletic Scholarship', 5551, 65);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (262, 'Sports Scholarship', 4823, 34);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (263, 'Community Service Scholarship', 3050, 20);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (264, 'Leadership Scholarship', 9607, 195);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (265, 'Leadership Scholarship', 2651, 178);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (266, 'International Student Scholarship', 2111, 29);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (267, 'Science Scholarship', 4007, 35);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (268, 'Science Scholarship', 5227, 109);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (269, 'Arts Scholarship', 5316, 138);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (270, 'Leadership Scholarship', 5549, 107);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (271, 'International Student Scholarship', 1209, 100);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (272, 'Healthcare Scholarship', 5189, 42);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (273, 'International Student Scholarship', 1161, 197);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (274, 'Leadership Scholarship', 8010, 43);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (275, 'Women in Technology Scholarship', 6796, 123);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (276, 'Arts Scholarship', 5859, 134);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (277, 'Minority Scholarship', 4381, 160);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (278, 'Music Scholarship', 1367, 195);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (279, 'Financial Aid Scholarship', 7867, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (280, 'Minority Scholarship', 4084, 145);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (281, 'Community Service Scholarship', 4750, 66);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (282, 'Diversity Scholarship', 1989, 124);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (283, 'International Student Scholarship', 6982, 34);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (284, 'Leadership Scholarship', 8582, 47);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (285, 'International Student Scholarship', 7710, 139);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (286, 'International Student Scholarship', 6906, 123);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (287, 'Community Service Scholarship', 4829, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (288, 'STEM Scholarship', 9995, 43);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (289, 'Financial Aid Scholarship', 8934, 85);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (290, 'Creative Writing Scholarship', 3238, 165);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (291, 'Science Scholarship', 4956, 126);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (292, 'Diversity Scholarship', 6810, 174);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (293, 'Financial Aid Scholarship', 3715, 69);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (294, 'Diversity Scholarship', 6356, 56);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (295, 'Women in Technology Scholarship', 9302, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (296, 'Innovation Scholarship', 1793, 139);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (297, 'International Student Scholarship', 7618, 126);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (298, 'Athletic Scholarship', 4805, 126);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (299, 'STEM Scholarship', 4873, 38);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (300, 'Music Scholarship', 7656, 102);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (301, 'STEM Scholarship', 9884, 22);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (302, 'Excellence Scholarship', 7511, 194);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (303, 'Science Scholarship', 1053, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (304, 'Minority Scholarship', 3833, 138);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (305, 'International Student Scholarship', 2484, 41);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (306, 'Leadership Scholarship', 5853, 68);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (307, 'Financial Aid Scholarship', 2955, 167);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (308, 'Athletic Scholarship', 6051, 190);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (309, 'Music Scholarship', 2526, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (310, 'International Student Scholarship', 7643, 31);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (311, 'Community Service Scholarship', 1933, 33);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (312, 'Diversity Scholarship', 6421, 22);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (313, 'Healthcare Scholarship', 6580, 54);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (314, 'Music Scholarship', 2349, 28);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (315, 'Academic Achievement Scholarship', 4471, 63);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (316, 'Academic Achievement Scholarship', 7602, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (317, 'Minority Scholarship', 6732, 162);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (318, 'Healthcare Scholarship', 4967, 41);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (319, 'Sports Scholarship', 3546, 147);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (320, 'Community Service Scholarship', 1099, 42);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (321, 'Arts Scholarship', 7952, 33);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (322, 'Community Service Scholarship', 5493, 58);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (323, 'Athletic Scholarship', 2381, 138);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (324, 'Arts Scholarship', 7936, 149);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (325, 'STEM Scholarship', 5723, 36);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (326, 'Healthcare Scholarship', 8427, 49);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (327, 'Diversity Scholarship', 5240, 168);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (328, 'Arts Scholarship', 7023, 51);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (329, 'Innovation Scholarship', 7828, 153);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (330, 'Leadership Scholarship', 1605, 79);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (331, 'Creative Writing Scholarship', 1690, 154);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (332, 'Academic Achievement Scholarship', 7638, 128);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (333, 'Women in Technology Scholarship', 3397, 193);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (334, 'Financial Aid Scholarship', 1668, 167);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (335, 'Athletic Scholarship', 4439, 114);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (336, 'Athletic Scholarship', 8329, 159);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (337, 'Arts Scholarship', 2571, 111);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (338, 'Leadership Scholarship', 7626, 59);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (339, 'Athletic Scholarship', 3467, 27);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (340, 'Minority Scholarship', 4367, 108);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (341, 'Science Scholarship', 1313, 92);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (342, 'Healthcare Scholarship', 3925, 118);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (343, 'Science Scholarship', 6174, 132);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (344, 'Creative Writing Scholarship', 8508, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (345, 'Arts Scholarship', 9982, 196);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (346, 'Financial Aid Scholarship', 8250, 134);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (347, 'Excellence Scholarship', 6094, 58);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (348, 'Sports Scholarship', 7889, 73);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (349, 'Women in Technology Scholarship', 5770, 37);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (350, 'Excellence Scholarship', 6963, 38);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (351, 'Merit Scholarship', 9928, 155);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (352, 'International Student Scholarship', 1553, 86);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (353, 'International Student Scholarship', 2555, 110);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (354, 'Merit Scholarship', 9232, 44);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (355, 'Athletic Scholarship', 1891, 170);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (356, 'Sports Scholarship', 1940, 191);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (357, 'Arts Scholarship', 9608, 141);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (358, 'Sports Scholarship', 1445, 88);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (359, 'Merit Scholarship', 5086, 51);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (360, 'Science Scholarship', 3950, 153);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (361, 'Research Grant', 1989, 130);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (362, 'Leadership Scholarship', 8980, 62);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (363, 'Diversity Scholarship', 9589, 21);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (364, 'Healthcare Scholarship', 9708, 186);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (365, 'Excellence Scholarship', 4122, 53);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (366, 'Innovation Scholarship', 2309, 183);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (367, 'STEM Scholarship', 6444, 92);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (368, 'Music Scholarship', 9359, 181);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (369, 'Music Scholarship', 9113, 179);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (370, 'Minority Scholarship', 2889, 141);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (371, 'Financial Aid Scholarship', 9215, 86);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (372, 'Financial Aid Scholarship', 2172, 29);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (373, 'Healthcare Scholarship', 6876, 110);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (374, 'Sports Scholarship', 1138, 72);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (375, 'Music Scholarship', 4847, 44);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (376, 'International Student Scholarship', 5350, 155);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (377, 'Healthcare Scholarship', 9314, 34);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (378, 'International Student Scholarship', 3835, 140);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (379, 'Creative Writing Scholarship', 2495, 82);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (380, 'Minority Scholarship', 7054, 96);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (381, 'Financial Aid Scholarship', 8140, 50);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (382, 'Sports Scholarship', 3051, 164);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (383, 'Diversity Scholarship', 9812, 115);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (384, 'Community Service Scholarship', 8486, 90);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (385, 'Leadership Scholarship', 3152, 50);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (386, 'Music Scholarship', 3485, 101);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (387, 'Arts Scholarship', 5745, 116);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (388, 'Community Service Scholarship', 3078, 44);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (389, 'Arts Scholarship', 4944, 199);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (390, 'Athletic Scholarship', 2072, 129);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (391, 'Diversity Scholarship', 6051, 167);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (392, 'Sports Scholarship', 9443, 153);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (393, 'International Student Scholarship', 6761, 103);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (394, 'Healthcare Scholarship', 6858, 176);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (395, 'Leadership Scholarship', 3542, 100);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (396, 'Research Grant', 7012, 109);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (397, 'Excellence Scholarship', 2452, 107);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (398, 'Creative Writing Scholarship', 9292, 139);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (399, 'Music Scholarship', 6789, 77);
INSERT INTO Scholarship (Scholarship_ID, Name, Amount, AnnualHours) VALUES (400, 'Community Service Scholarship', 7310, 185);
